### ISSUE TITLE
Copy filled struct To GPU

### ISSUE THREAD

**Issue by RER009** [m4rs-mt/ILGPU#603]
Hello,

I'm trying to copy filled data structure from CPU to GPU. Depending of selected accelerator, I have not the same result (CPU|Cuda:OK  OpenCL:Not OK)

As example, I use the sample ILGPU.Samples/SimpleStructures and try to copy a single element from CPU memory to buffer before launch kernel. 
For OpenCL accelerator only, data is not copied into the buffer. 

See code below :
```c#
  using (var accelerator = Accelerator.Create(context, acceleratorId))
  {
      Console.WriteLine($"Performing operations on {accelerator}");
      var kernel = accelerator.LoadAutoGroupedStreamKernel<Index1, ArrayView<CustomDataType>>(MyKernel);
      using (var buffer = accelerator.Allocate<CustomDataType>(1024))
      {
          // Try to copy simple Data
          CustomDataType customData = new CustomDataType(5);
          buffer.CopyFrom(customData, 2);
          //

          // Launch buffer.Length many threads and pass a view to buffer
          kernel(buffer.Length, buffer.View);
          // Wait for the kernel to finish...
          accelerator.Synchronize();
      }
  }
```

Could you give me some advice?

Thanks in advance.

**Comment by MoFtZ** [comment]
hi @RER009.

How are you checking that the OpenCL buffer does not have the correct results? Allocating a buffer on the GPU does not zero-initialize the block of memory, so it may contain random values.

What device are you using for your OpenCL accelerator? On my computer, the only OpenCL device is the integrated GPU (Intel HD Graphics 630). Have you tried updating the drivers for this device? I have previously had issues using older drivers.

Also, which version of ILGPU are you using? There used to be [an issue](https://github.com/m4rs-mt/ILGPU/issues/258) with the OpenCL accelerator incorrectly running the kernel before the buffer copy operation completed. Have you tried updating to ILGPU v0.10.1?

**Comment by RER009** [comment]
hi MoFtZ,

I investigated this issue a little. 

In conclusion, there is an issue when I use debuging tools in Visual Studio.

When I try to watch the "View" property of memoryBuffer, I have different results depending of selected accelerator.
When I use GetAsArray() method,to retrieve a copy of data, all is is well filled in the array.

I don't know if View property can be used for debugging, but in conclusion data is well filled.

Thanks for your support.

**Comment by MoFtZ** [comment]
Thanks for looking into the issue @RER009.

OK, so it sounds like this known issue #345, which was fixed in ILGPU v0.10.x. Note that the ILGPU.Samples repository is currently using ILGPU v0.9.2.

Please update to ILGPU v0.10.x.

**Comment by RER009** [comment]
I had already updated the version to 0.10.1 in ILGPU.Samples and it seems this little bug is still there.
For information, my device for OpenCl accelerator is Intel UHD 620.

**Comment by m4rs-mt** [comment]
@RER009 A workaround for this problem is to explicitly synchronize the accelerator (especially in OpenCL!) after each operation to be 100% sure that the correct information is displayed in the debugger. Alternatively, you can use the VS intermediate window and call `accelerator.Synchronize()` before inspecting the contents of a buffer.
